version: '3.7'
services:
  grafana:
    image: grafana/grafana-enterprise:8.4.7
    container_name: grafana-sentry-datasource
    ports:
      - '3000:3000'
    volumes:
      - ./pkg/mocker/testdata:/mock/grafana-sentry-datasource/testdata
      - ./:/var/lib/grafana/plugins/grafana-sentry-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_VIEWERS_CAN_EDIT=true
      - GF_ENTERPRISE_LICENSE_TEXT=$GF_ENTERPRISE_LICENSE_TEXT
      - E2E_GRAFANA_VERSION=${E2E_GRAFANA_VERSION}
      - GRAFANA_SENTRY_MOCK_SOURCE=local_mock