services:
  grafana:
    container_name: 'grafana-sentry-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.1.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-sentry-datasource
      - ./provisioning:/etc/grafana/provisioning
    environment:
      ORG_SLUG: ${ORG_SLUG}
      AUTH_TOKEN: ${AUTH_TOKEN}
